services:
  strfry:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strfry-relay
    ports:
      - "7777:7777"
    volumes:
      - ./strfry-ci.conf:/app/strfry.conf:ro
      - strfry-data:/app/strfry-db
    restart: unless-stopped

volumes:
  strfry-data:
